SELECT
    COUNT(*) AS TOTAL_RECORDS,
    SUM(
        CASE
            WHEN ABS(
                NVL(CURR_LIABILITIES,0)
                + NVL(CURR_MAT_LT_DEBT,0)
                - NVL(TOT_CURR_LIABILITIES,0)
            ) > 0.01
            THEN 1
            ELSE 0
        END
    ) AS CURRENT_LIABILITY_MISMATCHES
FROM VW_FACILITY_QUARTER;


SELECT DBMS_METADATA.GET_DDL(
    'VIEW',
    'VW_DQ_KPI',
    'SYSTEM'
) AS VIEW_DEFINITION
FROM DUAL;




SELECT
    YEAR_QTR,
    COUNT(*) AS TOTAL_QA_ROWS,
    COUNT(DISTINCT FAC_NO) AS DISTINCT_FACILITIES
FROM VW_FINANCIAL_QA
WHERE YEAR_QTR = 20261
GROUP BY YEAR_QTR;



SELECT COUNT(DISTINCT FAC_NO) AS DISTINCT_FACILITIES
FROM VW_FINANCIAL_QA;\


SELECT
    COUNT(DISTINCT FAC_NO) AS DISTINCT_FACILITIES,
    COUNT(*) AS FACILITY_QUARTER_ROWS
FROM VW_FINANCIAL_QA;


SELECT
    YEAR_QTR,
    FAC_NO,
    FINANCIAL_QA_STATUS
FROM VW_FINANCIAL_QA
ORDER BY FAC_NO, YEAR_QTR;



SELECT *
FROM (
    SELECT
        YEAR_QTR,
        FAC_NO,
        FINANCIAL_QA_STATUS
    FROM VW_FINANCIAL_QA
    ORDER BY FAC_NO, YEAR_QTR
)
WHERE ROWNUM <= 30;



SELECT
    COUNT(*) AS CHECKED,
    SUM(CASE WHEN FINANCIAL_QA_STATUS = 'PASS' THEN 1 ELSE 0 END) AS FIN_PASS,
    ROUND(
        100 * SUM(CASE WHEN FINANCIAL_QA_STATUS = 'PASS' THEN 1 ELSE 0 END)
        / COUNT(*),
        1
    ) AS PASS_PCT
FROM VW_FINANCIAL_QA;


SELECT YEAR_QTR,
    MEDIAN(NET_TOT) AS median_revenue,
       MEDIAN(TOTAL_MARGIN_PCT) AS median_total_margin,
       MEDIAN(CURRENT_RATIO) AS median_current_ratio,
       MEDIAN(DAYS_CASH_ON_HAND) AS median_days_cash,
       MEDIAN(LT_DEBT_TO_ASSET_PCT) AS median_lt_debt,
       COUNT(DISTINCT FAC_NO) AS facilities
FROM VW_FACILITY_RATIOS
GROUP BY YEAR_QTR
ORDER BY YEAR_QTR;



SELECT YEAR_QTR,
       MEDIAN(NET_TOT)                 AS median_net_tot,
       MEDIAN(TOTAL_OPERATING_REVENUE) AS median_total_op_rev
FROM   VW_FACILITY_RATIOS
GROUP  BY YEAR_QTR
ORDER  BY YEAR_QTR;



SELECT YEAR_QTR,
       MEDIAN(NET_TOT) AS median_net_tot,
       ROUND(MEDIAN(NET_TOT) / 1000000, 2) AS median_net_tot_m
FROM   VW_FACILITY_RATIOS
GROUP  BY YEAR_QTR
ORDER  BY YEAR_QTR;

SELECT ROUND(MEDIAN(NET_TOT) / 1000000, 2) AS all_quarters_m
FROM   VW_FACILITY_RATIOS;


SELECT ROUND(MEDIAN(TOTAL_OPERATING_REVENUE) / 1000000, 2) AS all_quarters_total_op_rev_m
FROM   VW_FACILITY_RATIOS;




SELECT CASE WHEN GROUPING(YEAR_QTR) = 1 THEN 'ALL' ELSE TO_CHAR(YEAR_QTR) END AS qtr,
       COUNT(DISTINCT FAC_NO)                             AS facilities,
       ROUND(MEDIAN(NET_TOT) / 1000000, 2)                AS med_net_patient_rev_m,
       ROUND(MEDIAN(OPERATING_MARGIN_PCT), 2)             AS med_operating_margin,
       ROUND(MEDIAN(TOTAL_MARGIN_PCT), 2)                 AS med_total_margin,
       ROUND(MEDIAN(CURRENT_RATIO), 2)                    AS med_current_ratio,
       ROUND(MEDIAN(DAYS_CASH_ON_HAND), 2)                AS med_days_cash,
       ROUND(MEDIAN(LT_DEBT_TO_ASSET_PCT), 2)             AS med_lt_debt
FROM   VW_FACILITY_RATIOS
GROUP  BY GROUPING SETS ((YEAR_QTR), ())
ORDER  BY GROUPING(YEAR_QTR), YEAR_QTR;





WITH q AS (
  SELECT YEAR_QTR,
         COUNT(DISTINCT FAC_NO)          AS facilities,
         MEDIAN(NET_TOT)                 AS rev,
         MEDIAN(TOTAL_MARGIN_PCT)        AS tm,
         MEDIAN(CURRENT_RATIO)           AS cr,
         MEDIAN(DAYS_CASH_ON_HAND)       AS dc,
         MEDIAN(LT_DEBT_TO_ASSET_PCT)    AS ltd
  FROM   VW_FACILITY_RATIOS
  GROUP  BY YEAR_QTR
)
SELECT YEAR_QTR,
       facilities - LAG(facilities) OVER (ORDER BY YEAR_QTR)                    AS d_facilities,
       ROUND((rev - LAG(rev) OVER (ORDER BY YEAR_QTR)) / 1000000, 2)            AS d_rev_m,
       ROUND(tm  - LAG(tm)  OVER (ORDER BY YEAR_QTR), 2)                        AS d_total_margin_pp,
       ROUND(cr  - LAG(cr)  OVER (ORDER BY YEAR_QTR), 2)                        AS d_current_ratio,
       ROUND(dc  - LAG(dc)  OVER (ORDER BY YEAR_QTR), 1)                        AS d_days_cash,
       ROUND(ltd - LAG(ltd) OVER (ORDER BY YEAR_QTR), 2)                        AS d_lt_debt_pp
FROM   q
ORDER  BY YEAR_QTR;





SELECT
    YEAR_QTR,

    ROUND(NET_TOT / 1000000, 2) AS HOSPITAL_NET_REVENUE_M,

    ROUND(PEER_MEDIAN_NET_TOT / 1000000, 2) AS PEER_MEDIAN_REVENUE_M,

    ROUND(
        100 * (NET_TOT - PEER_MEDIAN_NET_TOT)
        / NULLIF(PEER_MEDIAN_NET_TOT, 0),
        2
    ) AS REVENUE_VS_PEER_PCT,

    TYPE_HOSP,
    PEER_GROUP_SIZE

FROM VW_PEER_BENCHMARK

WHERE UPPER(FAC_NAME) = 'ADVENTIST HEALTH HOWARD MEMORIAL'

ORDER BY YEAR_QTR;






SELECT YEAR_QTR, OPERATING_MARGIN_PCT, PEER_MEDIAN_OPERATING_MARGIN
FROM   VW_PEER_BENCHMARK
WHERE  UPPER(FAC_NAME) LIKE '%HOWARD MEMORIAL%'
ORDER  BY YEAR_QTR;

SELECT METRIC_NAME, HOSPITAL_TXT, PEER_TXT, DIFF_TXT, PCT_DIFF_TXT, STATUS
FROM   VW_PEER_METRICS_LONG
WHERE  UPPER(FAC_NAME) LIKE '%HOWARD MEMORIAL%' AND YEAR_QTR = 20253
ORDER  BY METRIC_SORT;



   SELECT ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY CURRENT_RATIO), 2) AS p95,
          ROUND(MAX(CURRENT_RATIO), 2) AS max_val
   FROM   VW_PEER_BENCHMARK WHERE TYPE_HOSP = 'Comparable' AND YEAR_QTR = 20261;
   
   
   
   SELECT *
   FROM VW_PEER_INSIGHTS;
   
   
   
   
   
   
   SELECT
    COLUMN_ID,
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'VW_RISK_KPI'
ORDER BY COLUMN_ID;